CREATE TABLE user (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  password VARCHAR(32) NOT NULL,
  role     VARCHAR(32) NOT NULL,
  username VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stock (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  current_price NUMERIC(19, 2),
  last_update   timestamp default now(),
  name          VARCHAR(16),
  version       BIGINT,
  PRIMARY KEY (id)
);


ALTER TABLE user
  ADD CONSTRAINT UK_sb8bbouer5wak8vyiiy4pf2bx UNIQUE (username);
ALTER TABLE stock
  ADD CONSTRAINT UK_9fjf4aj1d5f2m6wi2uqmdan0a UNIQUE (name);


INSERT INTO user VALUES (NULL, 'abcde', 'UPDATER', 'tester1');
INSERT INTO user VALUES (NULL, 'qwert', 'UPDATER', 'tester2');

INSERT INTO stock VALUES (NULL, 23.34, now(), 'TEST.A',1);
INSERT INTO stock VALUES (NULL, 112.245, now(), 'TEST.B',1);


