CREATE TABLE user (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  password VARCHAR(32) NOT NULL,
  role     VARCHAR(32) NOT NULL,
  username VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE stock (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  current_price NUMERIC(19, 2),
  last_update   timestamp default now(),
  name          VARCHAR(16),
  version       BIGINT,
  PRIMARY KEY (id)
);


ALTER TABLE user
  ADD CONSTRAINT UK_sb8bbouer5wak8vyiiy4pf2bx UNIQUE (username);
ALTER TABLE stock
  ADD CONSTRAINT UK_9fjf4aj1d5f2m6wi2uqmdan0a UNIQUE (name);


INSERT INTO user VALUES (NULL, '2fa5c9caace083ed4e30852565241ec5', 'VIEWER', 'viewer1');
INSERT INTO user VALUES (NULL, '2fa5c9caace083ed4e30852565241ec5', 'VIEWER', 'viewer2');
INSERT INTO user VALUES (NULL, '2fa5c9caace083ed4e30852565241ec5', 'UPDATER', 'updater1');
INSERT INTO user VALUES (NULL, '2fa5c9caace083ed4e30852565241ec5', 'UPDATER', 'updater2');

INSERT INTO stock VALUES (NULL, 23.34, now(), 'STOCK.A',1);
INSERT INTO stock VALUES (NULL, 112.245, now(), 'STOCK.B',1);
INSERT INTO stock VALUES (NULL, 05.45, now(), 'STOCK.C',1);
INSERT INTO stock VALUES (NULL, 153.45, now(), 'STOCK.D',1);




